### ISSUE TITLE
Add p5.toio to p5.js website library page?

### ISSUE THREAD

**Issue by Qianqianye** [tetunori/p5.toio#68]
Hi @tetunori! The p5.toio library is great. If you'd like to have it included on the [p5.js/libraries](https://p5js.org/libraries/) page, please submit this [form](https://docs.google.com/forms/d/e/1FAIpQLSdWWb95cfvosaIFI7msA7XC5zOEVsNruaA5klN1jH95ESJVcw/viewform). Thank you!

**Comment by tetunori** [comment]
Hi @Qianqianye! thanks for the request.
After I update the library slightly, I will submit via the form you mentioned!

**Comment by tetunori** [comment]
Hi @Qianqianye, I have just submitted 2 libraries for p5.js, p5.toio and [BMWalker.js](https://github.com/tetunori/BMWalker.js), via the form. Could you confirm them?

Thanks for your daily contributions for p5.js!

**Comment by Qianqianye** [comment]
Thank you @tetunori! Yes, we have received the submission. I will reach out after we add them to the website. Look forward to seeing more people using the p5.toio and BMWalker.js.
